spring:
  cloud:
    nacos:
      server-addr: 211.69.197.52:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api2/product/**
          filters:
            - RewritePath=/api2/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api2/**
          filters:
            - RewritePath=/api2/(?<segment>.*),/renren-fast/$\{segment}

  application:
    name: mall-gateway


server:
  port: 88



