server:
  port: 9000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://211.69.197.52:3306/mall_oms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 211.69.197.52:8848
  application:
    name: mall-order

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto